import {
	ArrowDown,
	ArrowLeft,
	ArrowRight,
	ArrowUp,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Compass,
	Expand,
	ExternalLink,
	Focus,
	Globe,
	Grid,
	Home,
	Layout,
	Link,
	List,
	Map as MapIcon,
	MapPin,
	Maximize,
	Menu,
	Minimize,
	Navigation,
	PanelLeft,
	PanelRight,
	Search,
	Shrink,
	Sidebar,
	Target,
	ZoomIn,
	ZoomOut
} from 'lucide-react'

import { type IconData } from './types'
import { createIconData } from '@/lib/helpers/icon/createIconData'

export const NAVIGATION_ICONS: IconData[] = [
	createIconData('Home', Home, 'navigation'),
	createIconData('Search', Search, 'navigation'),
	createIconData('Menu', Menu, 'navigation'),
	createIconData('ChevronLeft', ChevronLeft, 'navigation'),
	createIconData('ChevronRight', ChevronRight, 'navigation'),
	createIconData('ChevronUp', ChevronUp, 'navigation'),
	createIconData('ChevronDown', ChevronDown, 'navigation'),
	createIconData('ArrowLeft', ArrowLeft, 'navigation'),
	createIconData('ArrowRight', ArrowRight, 'navigation'),
	createIconData('ArrowUp', ArrowUp, 'navigation'),
	createIconData('ArrowDown', ArrowDown, 'navigation'),
	createIconData('Navigation', Navigation, 'navigation'),
	createIconData('Compass', Compass, 'navigation'),
	createIconData('Map', MapIcon, 'navigation'),
	createIconData('MapPin', MapPin, 'navigation'),
	createIconData('Globe', Globe, 'navigation'),
	createIconData('Link', Link, 'navigation'),
	createIconData('ExternalLink', ExternalLink, 'navigation'),
	createIconData('Maximize', Maximize, 'navigation'),
	createIconData('Minimize', Minimize, 'navigation'),
	createIconData('Expand', Expand, 'navigation'),
	createIconData('Shrink', Shrink, 'navigation'),
	createIconData('ZoomIn', ZoomIn, 'navigation'),
	createIconData('ZoomOut', ZoomOut, 'navigation'),
	createIconData('Focus', Focus, 'navigation'),
	createIconData('Target', Target, 'navigation'),
	createIconData('Layout', Layout, 'navigation'),
	createIconData('Sidebar', Sidebar, 'navigation'),
	createIconData('PanelLeft', PanelLeft, 'navigation'),
	createIconData('PanelRight', PanelRight, 'navigation'),
	createIconData('Grid', Grid, 'navigation'),
	createIconData('List', List, 'navigation')
]
