import {
  Plus,
  Minus,
  Edit,
  Save,
  Trash2,
  Download,
  Upload,
  Share,
  Copy,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Shield,
  CheckCircle,
  XCircle,
  X,
  RefreshCw,
  RotateCcw,
  Play,
  Pause,
  SkipBack,
  SkipForward,
  Filter,
  SortAsc,
  SortDesc,
  MoreHorizontal,
  MoreVertical,
  Settings,
  Bell,
  Bookmark,
  Archive,
  Send,
  Scan,
  QrCode,
  Printer,
  Paperclip,
} from "lucide-react";

import { type IconData } from "./types";
import { createIconData } from "@/lib/utils/icon";

export const ACTION_ICONS: IconData[] = [
  createIconData("Plus", Plus, "actions"),
  createIconData("Minus", Minus, "actions"),
  createIconData("Edit", Edit, "actions"),
  createIconData("Save", Save, "actions"),
  createIconData("Trash2", Trash2, "actions"),
  createIconData("Download", Download, "actions"),
  createIconData("Upload", Upload, "actions"),
  createIconData("Share", Share, "actions"),
  createIconData("Copy", Copy, "actions"),
  createIconData("Eye", Eye, "actions"),
  createIconData("EyeOff", EyeOff, "actions"),
  createIconData("Lock", Lock, "actions"),
  createIconData("Unlock", Unlock, "actions"),
  createIconData("Shield", Shield, "actions"),
  createIconData("CheckCircle", CheckCircle, "actions"),
  createIconData("XCircle", XCircle, "actions"),
  createIconData("X", X, "actions"),
  createIconData("RefreshCw", RefreshCw, "actions"),
  createIconData("RotateCcw", RotateCcw, "actions"),
  createIconData("Play", Play, "actions"),
  createIconData("Pause", Pause, "actions"),
  createIconData("SkipBack", SkipBack, "actions"),
  createIconData("SkipForward", SkipForward, "actions"),
  createIconData("Filter", Filter, "actions"),
  createIconData("SortAsc", SortAsc, "actions"),
  createIconData("SortDesc", SortDesc, "actions"),
  createIconData("MoreHorizontal", MoreHorizontal, "actions"),
  createIconData("MoreVertical", MoreVertical, "actions"),
  createIconData("Settings", Settings, "actions"),
  createIconData("Bell", Bell, "actions"),
  createIconData("Bookmark", Bookmark, "actions"),
  createIconData("Archive", Archive, "actions"),
  createIconData("Send", Send, "actions"),
  createIconData("Scan", Scan, "actions"),
  createIconData("QrCode", QrCode, "actions"),
  createIconData("Printer", Printer, "actions"),
  createIconData("Paperclip", Paperclip, "actions"),
];
